"""init

Revision ID: a0c1bfc91dda
Revises: 
Create Date: 2026-08-25 22:27:30.982591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0c1bfc91dda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('glassdoor_rating', sa.Float(), nullable=True),
    sa.Column('glassdoor_summary', sa.String(), nullable=True),
    sa.Column('company_url', sa.String(), nullable=True),
    sa.Column('company_logo_url', sa.String(), nullable=True),
    sa.Column('company_linkedin_url', sa.String(), nullable=True),
    sa.Column('record_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('record_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('JobListing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('job_type', sa.Enum('full_time', 'part_time', 'contract', 'internship', 'other', name='jobtype'), nullable=True),
    sa.Column('category', sa.Enum('software_engineering', 'web_development', 'mobile_development', 'frontend_development', 'backend_development', 'full_stack_development', 'data_science', 'data_analytics', 'data_engineering', 'machine_learning', 'ai_engineering', 'devops', 'cloud_engineering', 'site_reliability', 'cybersecurity', 'networking', 'systems_administration', 'database', 'qa_testing', 'automation_testing', 'ui_ux_design', 'product_design', 'it_support', 'it_operations', 'solutions_architecture', 'software_architecture', 'product_management', 'project_management', 'business_analysis', 'technical_writing', 'erp_crm', 'embedded_systems', 'iot', 'blockchain_web3', 'game_development', 'it_management', 'other', name='jobcategory'), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('max_salary', sa.Float(), nullable=True),
    sa.Column('avg_salary', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(), nullable=True),
    sa.Column('salary_frequency', sa.Enum('monthly', 'annually', 'contract', 'hourly', name='salaryfrequency'), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('required_skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('preferred_skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('experience_level', sa.Enum('intern', 'entry', 'junior', 'mid', 'senior', 'lead', 'staff', 'principal', 'architect', 'manager', 'director', 'executive', 'other', name='experiencelevel'), nullable=True),
    sa.Column('min_experience_years', sa.Integer(), nullable=True),
    sa.Column('education_requirements', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('record_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['Run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_source_ext_id', 'JobListing', ['source', 'external_id'], unique=False)
    op.create_index('ix_joblisting_category', 'JobListing', ['category'], unique=False)
    op.create_index('ix_joblisting_job_type', 'JobListing', ['job_type'], unique=False)
    op.create_index('ix_joblisting_posted_at', 'JobListing', ['posted_at'], unique=False)
    op.create_index('ix_joblisting_source', 'JobListing', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_joblisting_source', table_name='JobListing')
    op.drop_index('ix_joblisting_posted_at', table_name='JobListing')
    op.drop_index('ix_joblisting_job_type', table_name='JobListing')
    op.drop_index('ix_joblisting_category', table_name='JobListing')
    op.drop_index('idx_source_ext_id', table_name='JobListing')
    op.drop_table('JobListing')
    op.drop_table('Run')
    op.drop_table('Company')
    # ### end Alembic commands ###
