"""add embeddings column

Revision ID: b73a34c1c49a
Revises: a0c1bfc91dda
Create Date: 2026-08-26 17:00:46.408360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b73a34c1c49a'
down_revision: Union[str, Sequence[str], None] = 'a0c1bfc91dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('JobListing', sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column('JobListing', sa.Column('canonical_job_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_joblisting_source_external_id', 'JobListing', ['source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_joblisting_source_external_id', 'JobListing', type_='unique')
    op.drop_column('JobListing', 'canonical_job_id')
    op.drop_column('JobListing', 'embedding')
    # ### end Alembic commands ###
